version: '3.8'
services:
  db:
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "${PORT}:8080"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  db_data:
