// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Message struct {
	ID        int32
	Content   string
	UserIp    string
	CreatedAt sql.NullTime
}
